spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/testdatabase
    username: testuser
    password: testpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  session:
    timeout: 60m

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  access-key: ${MINIO_ROOT_USER:minio_dev_user}
  secret-key: ${MINIO_ROOT_PASSWORD:minio_dev_secret}
  bucket-name: user-files
  user-root-directory: user-%d-files/

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost}
